### ISSUE TITLE
ORPort/DirPort address does not match descriptor address

### ISSUE THREAD

**Issue by kberanek** [nusenu/ansible-relayor#101]
Filing this issue per request in https://github.com/nusenu/ansible-relayor/issues/91.

When configuring a relay with a private IPv4 address and a NATed public IPv4 address the generated torrc uses the internal, private, address for ORPort and DirPort.  This results in log messages like the ones below.  This doesn't seem to actually cause any issues as far as I can tell.

```
Jan 22 16:00:44 tr2 Tor-10.2.107.87_8443[25613]: The IPv4 ORPort address 10.2.107.87 does not match the descriptor address 212.47.234.192. If you have a static public IPv4 address, use 'Address <IPv4>' and 'OutboundBindAddress <IPv4>'. If you are behind a NAT, use two ORPort lines: 'ORPort <PublicPort> NoListen' and 'ORPort <InternalPort> NoAdvertise'.
Jan 22 16:00:48 tr2 Tor-10.2.107.87_443[25656]: The IPv4 DirPort address 10.2.107.87 does not match the descriptor address 212.47.234.192. If you have a static public IPv4 address, use 'Address <IPv4>' and 'OutboundBindAddress <IPv4>'. If you are behind a NAT, use two DirPort lines: 'DirPort <PublicPort> NoListen' and 'DirPort <InternalPort> NoAdvertise'.
```

**Comment by nusenu** [comment]
Thanks for filing this.
What is your platform and tor version?

**Comment by kberanek** [comment]
These logs came from a Debian 8.7 x86_64 host running tor 2.9.8.  Slightly more detailed information below.

```
$ cat /etc/debian_version 
8.7
$ uname -a
Linux tr2 4.5.1-std-1 #1 SMP Mon Apr 18 19:58:58 UTC 2016 x86_64 GNU/Linux
$ tor --version
Tor version 0.2.9.8 (git-a0df013ea241b026).
```

**Comment by nusenu** [comment]
I assume you are behind a "1:1" NAT (one private IP is NATed to a public
IP and there are as many private IPs as public IPs), but could you reply
directly to teor's question on tor-dev@lists.torproject.org?

https://lists.torproject.org/pipermail/tor-dev/2017-January/011811.html

thanks!

**Comment by kberanek** [comment]
I've replied to the tor-dev thread.  As I mentioned in that email, it does
behave as 1:1 NAT as far as I can tell.

**Comment by nusenu** [comment]
Ok, so according to teor it is fine to ignore this log entry, but if I understood your setup correctly you have two IPs directly on the host and that could cause troubles in another way, could you paste the output of the following command for clarity - thanks!
```ansible -m setup -a filter=ansible_all_ipv4_addresses <yourserver>```

**Comment by kberanek** [comment]
Sorry for the delay.  I've been out of town this past week.  There's only a single private IP the host actually knows about.  The NAT is done somewhere upstream of these machines.
```
> ansible -m setup -a filter=ansible_all_ipv4_addresses tr2
tr2 | SUCCESS => {
    "ansible_facts": {
        "ansible_all_ipv4_addresses": [
            "10.2.107.87"
        ]
    }, 
    "changed": false
}
```
