### ISSUE TITLE
don't run more than 2 instances per public IPs and support private IPs

### ISSUE THREAD

**Issue by nusenu** [nusenu/ansible-relayor#102]
https://github.com/nusenu/ansible-relayor/issues/91#issuecomment-274934349

If the server has public and private IPv4 addresses (all listed in ansible_all_ipv4_addresses) we currently use all of them, which is not what we want if the private IP gets NATed to the public IP. In such an (unlikely) environment we would create 4 instances with a single public IPv4 address only - which is bad.
to avoid this:
use exclusively public IPv4 addresses by default, if we have no public IPv4 address use a single private IPv4 address (assume we are NATed to a single public IP and run only two instances).
optional:
provide a var to use all private IPv4 addresses (in that case the operator has to make sure that every private IPv4 address has a public IPv4 address it gets NATed to).

**Comment by kberanek** [comment]
This seems like a pretty reasonable solution and it sounds like it should work well for all of my relays.  I'll test it out once I'm back home tomorrow.
