### ISSUE TITLE
More detailed explanation of what should be contained in the `tor.yml` file in the README

### ISSUE THREAD

**Issue by duelle** [nusenu/ansible-relayor#111]
Would it be possible to go into detail what should/could be in the `tor.yml` file that is mentioned in the README file?
Especially for newbies to ansible, like I am, this could be really helpful to know what should go in there and maybe give a simple example for this.

Thanks for the great work!

**Comment by nusenu** [comment]
Hi, 
thanks for your input.

We have playbook examples on the wiki page:
https://github.com/nusenu/ansible-relayor/wiki/relayor-playbook-examples

Does that help?

**Comment by duelle** [comment]
Thank you for the fast reply!
Yeah, it gives me an idea on what should be in there I think.
In practice I would put the vars I want to set together in one `vars` section, right?

What would be helpful for me in the role of a newbie, would be an example on how to setup a set of different machines in terms of OS and creating a corresponding playbook.
Something like `Getting started`:
1. Add machines to to inventory (maybe link to inventory doc of ansible)
2. Install roles via ansible galaxy
3. Define playbook (simple example with some vars in it - maybe combined version of the examples in the wiki)
4. How to use/set the OS tags
5. Example for initial setup and reconfiguration

I'd be happy to contribute to this by extending such examples as soon as I figured out on how to do this myself. However, I would totally understand if you assume someone to have more basic knowledge of ansible and would not want to include such basic stuff.

**Comment by nusenu** [comment]
Something like that is already on my todo list and I started writing it.
It will be released together with  the 0.2.0 release.

https://lists.torproject.org/pipermail/tor-relays/2017-January/011775.html

**Comment by duelle** [comment]
Ok, great. Thanks a lot!

**Comment by nusenu** [comment]
@duelle 
https://medium.com/@nusenu/deploying-tor-relays-with-ansible-6612593fa34d
