### ISSUE TITLE
macOS (control machine): 'openssl sha256' requires 'sha256sum' to be available

### ISSUE THREAD

**Issue by colinsullivan** [nusenu/ansible-relayor#118]
Two OS X specific issues, both related to how OS X linux utilities differ ever so slightly...

1. openssl command requires the `sha256sum` utility, which is not installed on OS X by default.

To install it:

```
brew install coreutils
ln -s /usr/local/bin/gsha256sum /usr/local/bin/sha256sum
```

2. The bash command parsing the output of the hash ([here](https://github.com/nusenu/ansible-relayor/blob/master/tasks/configure.yml#L34) and [here](https://github.com/nusenu/ansible-relayor/blob/master/tasks/configure.yml#L140)) leaves whitespace on OS X, so the step fails because the local and remote keys look different.

I added `xargs` which by default does nothing but strip whitespace.

**Comment by nusenu** [comment]
Hi Colin,
thank you for your reports. 
I opened #120 for (2), this issue will be for (1).

Please file every issue separately in the future.

**Comment by nusenu** [comment]
@colinsullivan: Does `openssl sha1* filepath` work without additional steps? What macOS version are you on?

*) has security issues but since current tor uses SHA1 anyway I guess this is not a show stopper.

**Comment by nusenu** [comment]
> I couldn't reproduce this issue, everything just works. I don't have coreutils installed and I'm running macOS 10.12.5 (16F73).

thanks for trying to reproduce this, appreciated.

Could you add your used ansible and relayor version (or git revision),
thanks.

**Comment by acacs** [comment]
Hey,

I'm using ansible 2.3.0.0 and relayor v0.2.1-13-g4c2d82b.

**Comment by acacs** [comment]
One thing that I forgot to mention here is that I'm using homebrew openssl. With macOS openssl I had no luck, neither using Colin's proposed changes or trying what you suggested, nusenu.

**Comment by nusenu** [comment]
@acacs  
What openssl version does macOS 10.12 ship?
Can you provide a sample output of macOS' openssl:
```
openssl sha256 -r /some/public/file
```
(while coreutils are NOT installed)

thanks!

**Comment by acacs** [comment]
Hi @nusenu 
This is what I have for openssl shipped with macOS:

```
$ openssl version
OpenSSL 0.9.8zh 14 Jan 2016
```

```
$ openssl sha256 -r teste.txt
openssl:Error: 'sha256' is an invalid command
```

```
$ openssl sha1 -r teste.txt
unknown option '-r'
```

Looks like there's no support for sha256 and for sha1 it doesn't have option `-r`:

```
$ openssl sha1 teste.txt
SHA1(teste.txt)= 9dc628289966d144c1a5fa20dd60b1ca1b9de6ed
```

**Comment by nusenu** [comment]
> Hi @nusenu 
> This is what I have for openssl shipped with macOS:
> 
> ```
> $ openssl version
> OpenSSL 0.9.8zh 14 Jan 2016
> ```


> Looks like there's no support for sha256 and for sha1 it doesn't have option `-r`:

thanks for that info.

So we should figure out what is the first version of openssl that
supports `sha256` and `-r` and document that requirement in the README
