### ISSUE TITLE
macOS (control machine): whitespace causes false-positive on duplicate key check

### ISSUE THREAD

**Issue by nusenu** [nusenu/ansible-relayor#120]
split from #118: (reported by @colinsullivan)
>The bash command parsing the output of the hash ([here](https://github.com/nusenu/ansible-relayor/blob/master/tasks/configure.yml#L34) and [here](https://github.com/nusenu/ansible-relayor/blob/master/tasks/configure.yml#L140)) leaves whitespace on OS X, so the step fails because the local and remote keys look different.

>I added xargs which by default does nothing but strip whitespace.

Related: #119 

Thanks for your report.

This looks like a duplicate of #89.

f385dcd843a17587578c7422680ffbdba1b4aabd was supposed to fix this.
In [1] @rdkr mentioned that the fix works for him.

@colinsullivan: What OS/ansible/relayor versions are you running?

Could you paste an 'ansible-playbook -vvv' output using relayor v0.2.1?

[1] https://github.com/nusenu/ansible-relayor/pull/88#issuecomment-268623551

**Comment by nusenu** [comment]
@colinsullivan: Could you run this test playbook and paste the output here? thanks!

```
---
- hosts: 127.0.0.1
  connection: local

  tasks:

  - set_fact: 
     dupcount: "   0     "

  - debug: var=dupcount

  - debug: var=dupcount|int(1)

  - name: Expected to SKIP
    fail: msg="BUG!"
    when: dupcount|int(1) != 0
  
  - name: Expected to FAIL
    fail: msg="Expected to FAIL"
    when: dupcount != "0"
```

**Comment by acacs** [comment]
Hi,

I couldn't reproduce this issue. I'm running macOS 10.12.5 (16F73).

**Comment by nusenu** [comment]
Augusto Amaral:
> Hi,
> 
> I couldn't reproduce this issue. I'm running macOS 10.12.5 (16F73).


thanks for trying to reproduce this, appreciated.

Could you add your used ansible and relayor version (or git revision),
thanks.

**Comment by acacs** [comment]
Hi nusenu,

I'm using ansible 2.3.0.0 and relayor v0.2.1-13-g4c2d82b.

**Comment by nusenu** [comment]
@colinsullivan does it work for you as well?

**Comment by nusenu** [comment]
since it works for @acacs and we didn't hear back from @colinsullivan I'm closing this.
