### ISSUE TITLE
Preferred way of providing translations

### ISSUE THREAD

**Issue by anadahz** [nusenu/ansible-relayor#124]
It seems that some people would like to translate the README of ansible-relayor in different languages.
Is there a preferred way to provide translations of the README and perhaps other useful text?

**Comment by nusenu** [comment]
Hi @anadahz,
thanks for your interest in relayor. 
To be honest I didn't expect that someone would like to translate the README :) 
Who would like to translate it and to what languages?
Is there a  "default" way to do this for github READMEs?
Do you use (they) Transifex already?

**Comment by anadahz** [comment]
Hello!
> Who would like to translate it and to what languages?

People from the (Tor) community. :)
Languages: Portuguese and Spanish
> Is there a "default" way to do this for github READMEs?

No idea, searched a bit but didn't find anything useful.

> Do you (/they) use Transifex already?

Well we could use Transifex if there is an integration with github README's

**Comment by nusenu** [comment]
Do you feel there is actual demand for languages other than EN? Or what is the motivation?

**Comment by anadahz** [comment]
> Do you feel there is actual demand for languages other than EN? (What is the motivation?)

A guide for people that English is not their first language and would like to provision and setup a Tor relay as fast and reproducible as possible.

**Comment by nusenu** [comment]
maybe translating https://medium.com/@nusenu/deploying-tor-relays-with-ansible-6612593fa34d would be more useful to new users?

**Comment by acacs** [comment]
Hi. I started a pt-br translation [here](https://pad.riseup.net/p/Tn0XfgC9VZxJ).

Can we have the medium post referenced in the readme and then link to the translations in the medium post? I'm thinking about how to let people know about the translations when they visit this repo.

**Comment by nusenu** [comment]
I updated this part in the blogpost to make it more timeless:

this:
> The tor version on the control machine must be at least tor v0.2.7.x (tor v0.2.5.x in debian stable is to old because it lacks Ed25519/OfflineMasterKeys support).
The ansible version must (currently) be at >=v2.1.4 or >=v2.2.1. 
Older versions have known vulnerabilities and relayor will refuse to work with them.

got replaced by:
> Make sure your tor and ansible versions meet the [requirements](https://github.com/nusenu/ansible-relayor#requirements).

**Comment by anadahz** [comment]
Thanks @acacs that's really useful!

> I updated this part in the blogpost to make it more timeless: [...]

@nusenu Can we move the blog post sentence on top of the README ? For instance to the main part of the section, as right now is "hidden" in the installation section we should also find a way to add multiple language versions in the medium post?

**Comment by acacs** [comment]
@nusenu @anadahz 
I have the complete pt-br the translation [here](https://medium.com/@acacs/implantando-relays-tor-em-minutos-deef22d71248). Would be nice to have reviewers, I'm gonna reach out to tor-south irc channel.

**Comment by nusenu** [comment]
@acacs thanks!
I noticed that the code blocks have extra empty lines between every line, maybe you can trim that.

**Comment by acacs** [comment]
@nusenu fixed, thanks!

**Comment by anadahz** [comment]
Excellent, thanks @acacs and @nusenu .
