### ISSUE TITLE
/lib/systemd/system-generators/ should be created/exist first in Debian jessie

### ISSUE THREAD

**Issue by anadahz** [nusenu/ansible-relayor#125]
It seems that the directory `/lib/systemd/system-generators/` should be created/exist first. The [relevant part of the role](https://github.com/nusenu/ansible-relayor/blob/master/tasks/apt_prepare.yml#L55).

`# lsb_release -a`
```
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 8.6 (jessie)
Release:        8.6
Codename:       jessie
```

Failing role task excerpt:
```
TASK [ansible-relayor : Ensure custom systemd generator is in place (Debian/Ubuntu only)] ***********

fatal: [host]: FAILED! => {
    "changed": false,
    "checksum": "6d7eae61eb3e410148d3ab7dd421f56c3d5100e5",
    "failed": true,
    "invocation": {
        "module_args": {
            "attributes": null,
            "backup": false,
            "content": null,
            "delimiter": null,
            "dest": "/lib/systemd/system-generators/relayor-generator",
            "directory_mode": null,
            "follow": false,
            "force": true,
            "group": null,
            "mode": 493,
            "original_basename": "tor-generator",
            "owner": "root",
            "regexp": null,
            "remote_src": null,
            "selevel": null,
            "serole": null,
            "setype": null,
            "seuser": null,
            "src": "/root/.ansible/tmp/ansible-tmp-XXX/source",
            "unsafe_writes": null,
            "validate": null
        }
    },
    "msg": "Destination directory /lib/systemd/system-generators does not exist"
```

**Comment by nusenu** [comment]
Thank you for your report.
I looked into this and a default debian 8 installation (debian-8.8.0-amd64-netinst.iso)
has this folder (/lib/systemd/system-generator) created by default as part of the ```systemd``` package.
How did you manage to **not** have this folder?

Can you provide the output of:
```
dpkg -l systemd
dpkg -L systemd|grep generators$
ls -ld /lib/systemd/system-generator
```

btw: Are you using root to connect to the remote host?

**Comment by anadahz** [comment]
> How did you manage to not have this folder?

It seems that I th systemd package was not installed! 
This Debian stable version is originated from the proxmox VM templates.

Perhaps we should add the `systemd` package as a requirement?

> btw: Are you using root to connect to the remote host?

Yes, it's a disposable VM.

**Comment by nusenu** [comment]
> Perhaps we should add the systemd package as a requirement?

I used to have 'systemd' as a requirement [1], but since it is installed by default I removed it from the list. I'll re-add it, but I probably should not install something like systemd as part of this role.

[1] https://github.com/nusenu/ansible-relayor/blob/045a63b1c2f12dfa68c5676fc1d0ae3d5368cd63/README.md
