### ISSUE TITLE
increase min. tor version to 0.3.0.x once that version reaches OpenBSD and CentOS 7

### ISSUE THREAD

**Issue by nusenu** [nusenu/ansible-relayor#132]
tor v0.3.0.x is required by `tor_dedicatedExitIP`

**Comment by anadahz** [comment]
It seems that tor version 0.3.0.10 is already at OpenBSD (6.2):
https://ftp.openbsd.org/pub/OpenBSD/6.2/packages/amd64/tor-0.3.0.10.tgz

**Comment by nusenu** [comment]
thank you for the hint!

**Comment by anadahz** [comment]
> nusenu changed the title from increase min. tor version to 0.3.0.x once that version reaches OpenBSD (6.2) to increase min. tor version to 0.3.0.x once that version reaches CentOS 7

I will advice you to open a new ticket and close this one so it will be easier to track this in the future if required. Now the ticket title together with https://github.com/nusenu/ansible-relayor/issues/132#issuecomment-341916367 doesn't make much sense.

**Comment by nusenu** [comment]
closed due to #152
