### ISSUE TITLE
Add support for unattended-upgrades

### ISSUE THREAD

**Issue by anadahz** [nusenu/ansible-relayor#138]
This is a useful feature to people that are not actively administering or in a timely manner administer the relays. There are a number of security implications when using unattended upgrades or running outdated software on Tor relays.
In any case this feature should not be enabled by default.

**Comment by ypid** [comment]
I see a properly administrated and hardened server as the basis for this role and not something that this role should do. There are enough of good roles to do the rest. Also, unattended-upgrades is Debian based while ansible-relayor supports [a few other OSes as well](https://github.com/nusenu/ansible-relayor#supported-operating-systems).

May I point you to the nice [debops.unattended_upgrades](https://github.com/debops/ansible-unattended_upgrades) role and [DebOps](https://debops.org/) in general?

**Comment by nusenu** [comment]
While I agree that it is valuable, unattended-upgrades is outside the scope of this Tor role.
(a tor role should do as little as possible to the rest of the system configuration)

If there are no objections I'll close this issue.

**Comment by anadahz** [comment]
@ypid Thank you for your recommendations, [debops.unattended_upgrades](https://github.com/debops/ansible-unattended_upgrades) is only for *Debian systems but I guess similar roles should exist for other systems (eg. *BSD).

Do you think that unattended-upgrades may in any way interfere with ansible-relayor?

**Comment by nusenu** [comment]
It should not, if it does it is a bug in either role

**Comment by ypid** [comment]
Thats because `unattended-upgrades` is only for Debian systems. DebOps does not have such a cross platform approach as `nusenu.relayor` has it. Other roles probably exist, but I can not recommend one.

> Do you think that unattended-upgrades may in any way interfere with ansible-relayor?

No, I don’t think so. But I have no such setup running at the moment so I can not tell for certain. But I plan to do this and if there are issues they will be fixed.

**Comment by anadahz** [comment]
@ypid, @nusenu thank you for your comments.

I will try to combine both roles and see what happens. :)
My aim is to work on a dead-simple role(s) where a relay operator can use to maintain a reasonable secure and up to date Tor relay with the minimum effort.

**Comment by ypid** [comment]
> My aim is to work on a dead-simple role(s) where a relay operator can use to maintain a reasonable secure and up to date Tor relay with the minimum effort.

We are definitely talking about roles in plural then :) If you want to use Debian then I would say DebOps can provide all the basis. We really try to do it right. We also self-audited the project and keep it up to date at [CII Best Practices](https://bestpractices.coreinfrastructure.org/projects/237).
