### ISSUE TITLE
Make tor package state (currently 'present') configurable

### ISSUE THREAD

**Issue by anadahz** [nusenu/ansible-relayor#139]
IMHO every time the role is running all software running on the relay node should be upgraded as well.
Ideally we should have an upgrade tag for users to easily updated their relays.

**Comment by ypid** [comment]
At most the role should update tor when rerunning. But even that is not best practice in my eyes for an Ansible role. The admin can use thinks like unattended-upgrades to ensure this, ref: #138.

**Comment by nusenu** [comment]
Hello anadahz,
thank you for your input.
I actually did specifically choose 
```state: present```
over 
```state: latest```
because ```latest``` would cause a significant delay **everytime** this role runs (repo sync).
https://github.com/nusenu/ansible-relayor/blob/master/tasks/main.yml#L78

I added a note to the README.

**Comment by anadahz** [comment]
It may be tricky to some users using the role to provision an already running system with (probably) an outdated tor version. In this sense does it makes sense to add a minimum acceptable tor version (hardcoded) similar to the [tor_alpha_version](https://github.com/nusenu/ansible-relayor/blob/master/defaults/main.yml#L98) variable?

What about adding a task oriented tag that will explicitly update the packages upon usage?

**Comment by nusenu** [comment]
I'll make the state (currently set to "present") configurable so people
can choose to have it set to "latest" to ensure tor is updated to the
latest version everytime a full playbook run is invoked - but that will
be opt-in.

**Comment by nusenu** [comment]
While testing it I found out that
```state=latest```
is broken in ansible 2.4.0.0 (fixed in v2.4.1.0-0.4.rc2).

So I will wait till ansible 2.4.1.0 is released.

**Comment by nusenu** [comment]
implemented in:
https://github.com/nusenu/ansible-relayor/commit/80e3b26e5fe379b091b81e1f532f90c90e7839df

blocking upstream bug:
https://github.com/ansible/ansible/issues/32327

**Comment by nusenu** [comment]
short update:
It is unlikely this will ever be fixed since upstream is unlikely to support state=latest on all platforms.

**Comment by nusenu** [comment]
Upstream does not support state=latest for all platforms so we can not support it eighter.

**Comment by anadahz** [comment]
>Upstream does not support state=latest for all platforms so we can not support it eighter.

I still think that makes sense to add support for `state=latest` for supported platforms rather than dropping this feature just because this is broken for FreeBSD.

**Comment by nusenu** [comment]
Why not use the unattended-upgrades role? (which is IMHO a lot better
because it does not require anyone to run the ansible playbook to
upgrade regularly).

**Comment by anadahz** [comment]
IMHO when the relayor role provisions a new relay it should make sure that is using the latest available version of tor. It doesn't make much sense to deploy a new relay with an older version of tor just because this node happened to have a tor package installed and using the unattended-upgrades role is just one extra dependency that may have its own drawbacks and issues (as most ansible roles have).

By regularly running the relayor role (which should be the default if you don't want to end up with expired keys) you ensure that you are running an up-to-date version of tor and hopefully this may reduce the [relays running end-of-life Tor releases](https://nusenu.github.io/OrNetStats/eolrelays).

**Comment by nusenu** [comment]
https://github.com/nusenu/ansible-relayor/commit/8243aac60184570a2bc0a4432ba94a2446053096

not sure if this works as expected because the package module does not expose the update_cache argument of the apt module.

todo: update documentation (include info on what platform this is supported)

**Comment by nusenu** [comment]
you can now configure the package state on Linux based systems via
tor_package_state (this is not supported on BSDs)
8243aac60184570a2bc0a4432ba94a2446053096

**Comment by anadahz** [comment]
Great thanks @nusenu
