### ISSUE TITLE
tor_ExitNoticePage in multiple languages

### ISSUE THREAD

**Issue by anadahz** [nusenu/ansible-relayor#140]
Is adding support for multiple existing languages of the tor exit notice something that makes sense for the ansible-relayor role?

An idea will be to add some default template exit notices in different languages  (eg.  [Castellano](https://0xacab.org/tortola/exit-notice/blob/master/nodos/gabriela/index.html)) and using a variable to change the language specific tor exit HTML page.

**Comment by nusenu** [comment]
Hello anadahz,

thank you for your request.

This HTML file comes directly from upstream (torproject.org)
https://gitweb.torproject.org/tor.git/plain/contrib/operator-tools/tor-exit-notice.html

so if they ship some more language versions of it I'll incorporate it,
but I would like to avoid having to manage translations.

So the next step would be to file a ticket here:
https://trac.torproject.org
to translate the current tor-exit-notice.

**Comment by anadahz** [comment]
Thanks to your always prompt responses @nusenu !

> So the next step would be to file a ticket here:
https://trac.torproject.org
to translate the current tor-exit-notice.

https://trac.torproject.org/projects/tor/ticket/24100
