### ISSUE TITLE
Add support for manually specifying "Address" torrc option (for rare environments)

### ISSUE THREAD

**Issue by anadahz** [nusenu/ansible-relayor#141]
From the [README](https://github.com/nusenu/ansible-relayor/blob/master/README.md):
> * reconfigure - regenerates torrc files and reloads tor (requires previously configured tor instances)
Reconfigure tag

**Description**: Running the role with the `reconfigure` tag will not regenerating torrc file(s) even if new tor variables have been added.

**Expected behavior**: torrc file(s) should be update and include the new changes

**Actual behavior**: torrc file(s) are not touched, stat's Modify and Change tags
confirm this behavior

**Steps to reproduce**: Add a new tor variable in role playbook and run the role
with the `reconfigure` tag

**Comment by nusenu** [comment]
thank you for your report!

I'm unable to reproduce this, please provide the more information
to help me reproduce this:

* `ansible --version` output
* used relayor version
* ansible controller OS
* target host OS+version
* torrc file before running with reconfigure tag
* playbook before and after the change (or a diff)
* ansible-playbook command used

**Comment by anadahz** [comment]
>* `ansible --version` output

```
ansible 2.4.1.0
  config file = None
  configured module search path = [u'/home/user/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/user/.ansible-venv/local/lib/python2.7/site-packages/ansible
  executable location = /home/user/.ansible-venv/bin/ansible
  python version = 2.7.9 (default, Jun 29 2016, 13:08:31) [GCC 4.9.2]
```
>* used relayor version

`# git rev-parse HEAD`
```
828935ea70fd6ad0c39a705f8816bc50ff6be59f
```
>* ansible controller OS

Debian jessie

> * target host OS+version

`# cat /etc/*release`
```
PRETTY_NAME="Debian GNU/Linux 8 (jessie)"
NAME="Debian GNU/Linux"
VERSION_ID="8"
VERSION="8 (jessie)"
ID=debian
HOME_URL="http://www.debian.org/"
SUPPORT_URL="http://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```
> * torrc file before running with reconfigure tag

```
# ansible-relayor generated torrc configuration file
# Note: manual changes will be OVERWRITTEN on the next ansible-playbook run

OfflineMasterKey 1
RunAsDaemon 0
Log notice syslog
OutboundBindAddress IP_REDACTED
SocksPort 0
User _tor-IP_REDACTED_9000
DataDirectory /var/lib/tor-instances/IP_REDACTED_9000
ORPort IP_REDACTED:9000


DirPort IP_REDACTED:9001

SyslogIdentityTag IP_REDACTED_9000

ControlSocket 0
CookieAuthentication 0

Nickname Nickname_REDACTED

Sandbox 1
# we are an exit relay!
ExitRelay 1
ExitPolicy accept *:20-23,accept *:43,accept *:53,accept *:79-81,accept *:88,accept *:110,accept *:143,accept *:194,accept *:220,accept *:389,accept *:443,accept *:464,accept *:465,accept *:531,accept *:543-544,accept *:554,accept *:563,accept *:587,accept *:636,accept *:706,accept *:749,accept *:873,accept *:902-904,accept *:981,accept *:989-995,accept *:1194,accept *:1220,accept *:1293,accept *:1500,accept *:1533,accept *:1677,accept *:1723,accept *:1755,accept *:1863,accept *:2082,accept *:2083,accept *:2086-2087,accept *:2095-2096,accept *:2102-2104,accept *:3128,accept *:3389,accept *:3690,accept *:4321,accept *:4643,accept *:5050,accept *:5190,accept *:5222-5223,accept *:5228,accept *:5900,accept *:6660-6669,accept *:6679,accept *:6697,accept *:8000,accept *:8008,accept *:8074,accept *:8080,accept *:8082,accept *:8087-8088,accept *:8332-8333,accept *:8443,accept *:8888,accept *:9418,accept *:9999,accept *:10000,accept *:11371,accept *:19294,accept *:19638,accept *:50002,accept *:64738,reject *:12350,reject *:23456,reject *:33033,reject *:*
DirPortFrontPage /etc/tor/instances/tor-exit-notice.html

ContactInfo ContactInfo_REDACTED

MyFamily MyFamily_REDACTED
# end of torrc
```
> * playbook before and after the change (or a diff)

```
- hosts: host-group
  vars:
    tor_ExitRelay: True
    tor_ContactInfo: ContactInfo_REDACTED
    tor_AbuseEmailAddress: ContactInfo_REDACTED
    tor_signingkeylifetime_days: 30
    tor_ports:
      - { orport: 443, dirport: 80}
      - { orport: 9000, dirport: 9001}
  roles:
   - ansible-relayor
```
`# diff -u a b`
```
--- a
+++ b
@@ -8,6 +8,8 @@
     tor_ports:
       - { orport: 443, dirport: 80}
       - { orport: 9000, dirport: 9001}
+    tor_Address: IP_REDACTED
+    tor_OutboundBindAddress: IP_REDACTED
   roles:
    - ansible-relayor
```
> * ansible-playbook command used

`# ansible-playbook -i inventory playbook.yml --tags reconfigure --limit=host-groug`

**Comment by nusenu** [comment]
> +    tor_Address: IP_REDACTED

The torrc option "Address" is not supported (does not exist in the torrc
template of relayor).

Does auto detection (default) not work for you?

We are not setting it because it is not possible for us to automatically
to determine it and it is almost everytime better to use auto detection
than anything manual.

> +    tor_OutboundBindAddress: IP_REDACTED

You are trying to set OutboundBindAddress directly in a way not
supported by relayor. Depending on what you are trying to achieve you
might want to look into the vars:
- tor_ips
- tor_dedicatedExitIP (see the readme)

**Comment by anadahz** [comment]
> Does auto detection (default) not work for you?

> We are not setting it because it is not possible for us to automatically
to determine it and it is almost everytime better to use auto detection
than anything manual.

The auto detection of relayor does not work for me.
Excerpt from syslog:
```
tor Tor-INTERNAL_IP_REDACTED_9000[XXXX]: Your server (FALSE_EXTERNAL_IP_REDACTED:9001) has not managed to confirm that its DirPort is reachable. Relays do not publish descriptors until their ORPort and DirPort are reachable. Please check your firewalls, ports, address, /etc/hosts file, etc.
tor Tor-INTERNAL_IP_REDACTED_9000[XXXX]: The IPv4 ORPort address INTERNAL_IP_REDACTED does not match the descriptor address FALSE_EXTERNAL_IP_REDACTED. If you have a static public IPv4 address, use 'Address <IPv4>' and 'OutboundBindAddress <IPv4>'. If you are behind a NAT, use two ORPort lines: 'ORPort <PublicPort> NoListen' and 'ORPort <InternalPort> NoAdvertise'.
```
> You are trying to set OutboundBindAddress directly in a way not
supported by relayor. Depending on what you are trying to achieve you
might want to look into the vars:
> - tor_ips

From (https://github.com/nusenu/ansible-relayor/blob/master/defaults/main.yml#L14-L17):
```
# Limit the amount of used IP addresses 
# by default to 1, this limits the amount
# of generated Tor instances to 2 per host.
# Specifying tor_ips overwrites this limitation.
```
> - tor_dedicatedExitIP (see the readme)

From (https://github.com/nusenu/ansible-relayor/blob/master/README.md#role-variables):
```
* `tor_dedicatedExitIP` boolean
    - this feature **requires** tor version >= v0.3.0.3-alpha
    - only relevant for exit relays
    - automatically configures the [OutboundBindAddressExit](https://www.torproject.org/docs/tor-manual.html.en#OutboundBindAddressExit) tor feature (does not require you to manually specify the IP address to use)
    - this means tor will establish outbound exit connections on a separate IP(v4/v6) address (different from the IP announced in the consensus)
    - to make use of this feature you need more public IPv4 or IPv6 addresses than `tor_maxPublicIPs`
    - if this condition is not met we will abort
    - all instances on a host will use the same `OutboundBindAddressExit` address
    - manually specifying the IP address used by `OutboundBindAddressExit` is not supported
    - default: False
```

It seems that both variables do not allow to manually setup the `OutboundBindAddress`.

Which is the best possible suggested way to set a (correct) static IP in relayor?

**Comment by nusenu** [comment]
> The auto detection of relayor does not work for me.
> Excerpt from syslog:

Do you know why autodetection fails in your case?
Can you describe your IP / NAT setup?
Does it work if you add the
```Address```
line manually?

https://github.com/nusenu/ansible-relayor/wiki/Safe-to-ignore-failures-and-warnings
https://github.com/nusenu/ansible-relayor/issues/101

> From (https://github.com/nusenu/ansible-relayor/blob/master/defaults/main.yml#L14-L17)

This is the documentation for `tor_maxPublicIPs` not `tor_ips` but I was wrong about `tor_ips` anyway (I changed to `tor_v4ips`).
Example:
```
tor_v4ips:
 - 1.2.3.4
```
It is not documented because it is not actually supposed to be set manually, but after understanding your setup I might change my mind about that.

I'd like to understand your setup as well :)

**Comment by anadahz** [comment]
> Do you know why autodetection fails in your case?
The VM has an internal IP allocated and tor is not able to correctly detect it's external IP `FALSE_EXTERNAL_IP_REDACTED` (ref: https://github.com/nusenu/ansible-relayor/issues/141#issuecomment-341914393)

> Can you describe your IP / NAT setup?

I have quite limited information apart from:
* The VM has a int. IP (most probably using a NAT to forward to the outside world)
* The VM has been assigned an external IP that was given to me

> Does it work if you add the
Address
line manually?

It does work.

**Comment by nusenu** [comment]
Ok, I assume your environment NATs outbound traffic to another public IP
as inbound traffic.

Can you confirm that
- your server has only one IPv4 address ("ifconfig" output)
- that one IP address is a non-public (RFC1918) IP address
- the IP address you see when fetching http://checkip.dyndns.org/ from
your server does NOT match the external public IP "that was given to" you

If my assumptions about your setup are correct, you do not actually need
to change relayor's OutboundBindAddress behavior via `tor_v4ips`.

I'll very likely add "Address" torrc support for manual opt-in
configuration.

**Comment by anadahz** [comment]
>Can you confirm that
>- your server has only one IPv4 address ("ifconfig" output)

It has only one interface with one IPv4 address

>- that one IP address is a non-public (RFC1918) IP address

Non public IP

>- the IP address you see when fetching http://checkip.dyndns.org/ from
>your server does NOT match the external public IP "that was given to" you

The IP given by `checkip.dyndns.org` does not match the external (given) public IP.

**Comment by nusenu** [comment]
Ok, thanks for confirming.

I'll add "Address" support with the limitation that you can specify it
only once per server (so you can not run more than 2 instances) even if
you have multiple public IPs.

**Comment by nusenu** [comment]
6b34e70f5447dc8f0c05adc5d203780d344a5a1f should fix this.

Can you confirm?

**Comment by nusenu** [comment]
one moment I'll fix it (it is missing some {{}})

**Comment by anadahz** [comment]
> 6b34e70 should fix this.

> Can you confirm?

Confirm this patch fixes it. Thank you.
