### ISSUE TITLE
relayor fails to create tor systemd services on Debian jessie

### ISSUE THREAD

**Issue by anadahz** [nusenu/ansible-relayor#142]
**Host release**:
`# cat /etc/*release`
```
PRETTY_NAME="Debian GNU/Linux 8 (jessie)"
NAME="Debian GNU/Linux"
VERSION_ID="8"
VERSION="8 (jessie)"
ID=debian
HOME_URL="http://www.debian.org/"
SUPPORT_URL="http://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```
Ansible verbose failure error:
```
TASK [ansible-relayor : Ensure Tor instances are enabled and started (Linux/systemd)] *********
failed: [host] (item=[{u'ipv4': u'IPv4_REDACTED', u'ipv6': u'IPv6_REDACTED'}, {u'orport': ORPORT_REDACTED, u'dirport': DIRPORT_REDACTED}]) => {
    "changed": false, 
    "failed": true, 
    "invocation": {
        "module_args": {
            "arguments": "", 
            "enabled": true, 
            "name": "tor@IPv4_REDACTED_ORPORT_REDACTED.service", 
            "pattern": null, 
            "runlevel": "default", 
            "sleep": null, 
            "state": "started"
        }
    }, 
    "item": [
        {
            "ipv4": "IPv4_REDACTED", 
            "ipv6": "IPv6_REDACTED"
        }, 
        {
            "dirport": DIRPORT_REDACTED, 
            "orport": ORPORT_REDACTED
        }
    ], 
    "msg": "Could not find the requested service tor@IPv4_REDACTED_ORPORT_REDACTED.service: host"
}
```

**Comment by nusenu** [comment]
thanks for your report!

could you provide the playbook and ansible-playbook command you used?

**Comment by anadahz** [comment]
>could you provide the playbook and ansible-playbook command you used?

`# ansible-playbook -vvvv -i inventory playbook.yml --limit=host`

**Comment by nusenu** [comment]
no playbook?

**Comment by nusenu** [comment]
dpkg -l tor
systemctl status tor@*

would also be helpful

**Comment by anadahz** [comment]
>no playbook?

```
- hosts: hosts
  vars:
    tor_ExitRelay: False
    tor_signingkeylifetime_days: 30
    tor_ports:
      - { orport: ORPORT_REDACTED, dirport: DIRPORT_REDACTED}
  roles:
   - ansible-relayor
```
>dpkg -l tor

```
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name              Version       Architecture  Description
+++-=================-=============-=============-========================================
ii  tor               0.3.1.8-2~d80 amd64         anonymizing overlay network for TCP
```

>systemctl status tor@

```
Failed to get D-Bus connection: Unknown error -1
```

**Comment by nusenu** [comment]
anadahz:
>> systemctl status tor@

you are missing a "*"

> Failed to get D-Bus connection: Unknown error -1

ok, looks like your system has a general systemd problem unrelated to
relayor.

**Comment by anadahz** [comment]
This is a clean VM created with proxmox and manually installed systemd.
Not sure what could be the best way to provision a relay there with relayor.

See also #125.
Perhaps we should add an option for non systemd-capable systems or use this option when systemd fails.

**Comment by nusenu** [comment]
I'm sorry but systemd is and will remain a hard requirement for all
Linux platforms supported by relayor. Systemd is used by default
on all relayor supported Linux platforms and is crucial for its tor
multi-instance support.

**Comment by nusenu** [comment]
My understanding is that the problem described in this issues
arises from a systemd problem on the particular system installation
(systemctl commands fail as seen above) and not from a
relayor bug. Should there be no further information pointing to a
relayor bug I assume it is fine to close this issue.
