### ISSUE TITLE
Set host/instance ansible nicknames without the tor_nicknamefile variable

### ISSUE THREAD

**Issue by anadahz** [nusenu/ansible-relayor#143]
By default relayor sets the same nickname to 2 instances per host.
Is there a way to set the nicknames per host per instance without using the `tor_nicknamefile` variable that requires an external CSV file?

This way the relay(s) configuration could be configured from one location that makes sense to Ansible rather than using an external CSV file.

**Comment by nusenu** [comment]
Hi,

thank you for your request.

anadahz:
> By default relayor sets the same nickname to 2 instances per host. Is
> there a way to set the nicknames per host per instance without using
> the `tor_nicknamefile` variable that requires an external CSV file?

There is no other option than the CSV file.


> This way the relay(s) configuration could be configured from one
> location that makes sense to Ansible rather than using an external
> CSV file.

The CSV file is located on the control machine so it is in one central
location already.

**Comment by anadahz** [comment]
Thanks for your response

> The CSV file is located on the control machine so it is in one central
location already.

I just find not favorite to define options outside the Ansible playbook or inventory and use a separate file only to define the nickname of the relay and given the fact that there is a `tor_nickname` variable I'm sure there will a probably good reason behind this decision. :)

**Comment by nusenu** [comment]
Can you provide a fictive example playbook /  inventory that shows how you would specify per instance nicknames?

**Comment by anadahz** [comment]
```
# change default nickname per instance (default: 2/IP with same nickname)
tor_nicknames:
      - nickname-1
      - nickname-2
```
- When the variable `tor_nicknames` is set use it instead of `inventory_hostname`.
- Add `tor_nicknames` to the nested_loops of `confgure.yml`

- Add an if clause similar to this in torrc:
```
{% if tor_nicknamefile is defined %}
NickName {{ item.0.tor_nicknames | regex_replace('[^a-zA-Z0-9]', '') |truncate(19, True, '')}}
```
We can tweak this in case we don't want to change the inventory_hostname, personally I find it easier to identify a relay on a running system and be assured that I have set a NickName.

**Comment by nusenu** [comment]
anadahz:
> ```
> # change default nickname per instance (default: 2/IP with same nickname)
> tor_nicknames:
>       - nickname-1
>       - nickname-2
> ```

That does not specify which instance gets assigned which nickname and it
will not work with >2 instances.

**Comment by anadahz** [comment]
>That does not specify which instance gets assigned which nickname and it
will not work with >2 instances.

Similar to `tor_ports` you don't really specify which instance gets assigned to which port.
I guess something will need to happen in order to support >2 instances per host.

The default setting of having the same nickname per host is not that favorable if the issue is technical I'm sure we can find a solution.

**Comment by nusenu** [comment]
anadahz:
>> That does not specify which instance gets assigned which nickname and it
> will not work with >2 instances.
> 
> Similar to `tor_ports` you don't really specify which instance gets assigned to which port.

an instance is defined by IP:ORPort

> I guess something will need to happen in order to support >2 instances per host.

relayor supports >2 instances per host if you have more than one public
IPv4.

> The default setting of having the same nickname per host is not that favorable if the issue is technical I'm sure we can find a solution.

There is no default setting for tor_nickname.

I consider this non-csv per instance nicknames a cosmetic issue since
relayor supports per-instance nicknames already now.

**Comment by anadahz** [comment]
> an instance is defined by IP:ORPort

Is there a way to set a specific instance to use a specific IP:ORPort combination?

> There is no default setting for tor_nickname.

> I consider this non-csv per instance nicknames a cosmetic issue since
relayor supports per-instance nicknames already now.

Sometimes it's all about "cosmetic issues" :)

**Comment by nusenu** [comment]
anadahz:
>> an instance is defined by IP:ORPort
> Is there a way to set a specific instance to use a specific IP:ORPort combination?

If you want relayor to use a specific IP address and ORPort, yes that is
supported. Moving from one to another IP / ORPort is not supported and
requires manual steps (see migration guide), but this seems off-topic.

Unless someone wants to work on this I'm inclined to close this cosmetic
request.

**Comment by nusenu** [comment]
The current CSV file works for me, but feel free to submit a patch for review if you really hate that simple CSV file.
