### ISSUE TITLE
make ExitPolicy in generated torrc files more readable

### ISSUE THREAD

**Issue by nusenu** [nusenu/ansible-relayor#150]
Currently we generate a torrc file that puts the entire exit policy (potentially a very long string) into a single line.

Currently generated torrcs look like:
```
ExitPolicy accept *:22, accept *:43, accept *:53, accept *:79-81, accept *:88, ...
```

The nicer looking alternative (doing exactly the same):
```
ExitPolicy accept *:22
ExitPolicy accept *:43
ExitPolicy accept *:53
ExitPolicy accept *:79-81
ExitPolicy accept *:88
...
```

This change will likely **break backward compatibility** since we will make `tor_ExitPolicy` an array instead of a string.

It might also make sense to move the ExitPolicy to the end of the torrc file because it might be very long. 

fix looks like:
```
{% for entry in tor_ExitPolicy %}
ExitPolicy {{entry}}
{% endfor %}
```

**Comment by nusenu** [comment]
This branch should get some testing
https://github.com/nusenu/ansible-relayor/tree/multi-line_exit-policy

**Comment by Lirt** [comment]
For me using yaml list looks nicer and I find it more yamlish. It may require more characters and editing to write it however (for people not experienced in text editors).

tor_ExitPolicy:
  - accept *:20-21
  - accept *:22
  - accept *:23
  - accept *:43
  - accept *:53
  - accept *:79
  - accept *:80-81
  - accept *:88
  - accept *:110
  - accept *:143

**Comment by Lirt** [comment]
The list should have 2 spaces indentation as example above.

https://github.com/nusenu/ansible-relayor/commit/9d89f931374d00a5f176d6aae95381de164cf11d#diff-7eeda618087b49ae876084ab6c73fdbbR110
