### ISSUE TITLE
ERROR! 'index_var' is not a valid attribute for a LoopControl

### ISSUE THREAD

**Issue by ph3x** [nusenu/ansible-relayor#161]
```
$ ansible-playbook tor.yml -t renewkey -vvv
ansible-playbook 2.4.2.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/me/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible
  executable location = /usr/local/bin/ansible-playbook
  python version = 2.7.13 (default, Nov 24 2017, 17:33:09) [GCC 6.3.0 20170516]
Using /etc/ansible/ansible.cfg as config file
SUDO password: 
Parsed /home/me/git/ansible/hosts inventory source with ini plugin
statically imported: /home/me/git/ansible/roles/ansible-relayor/tasks/ip-list.yml
statically imported: /home/me/git/ansible/roles/ansible-relayor/tasks/configure.yml
ERROR! 'index_var' is not a valid attribute for a LoopControl

The error appears to have been in '/home/me/git/ansible/roles/ansible-relayor/tasks/configure.yml': line 215, column 5, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

  loop_control:
    index_var: loop_idx
    ^ here
```

**Comment by ypid** [comment]
`index_var` as introduced in Ansible 2.5.0 but the docs are not yet up-to-date as it seems. I opened #162 to fix this.

**Comment by nusenu** [comment]
Robin Schneider:
> `index_var` as introduced in Ansible 2.5.0 but the docs are not yet up-to-date as it seems. I opened #162 to fix this.
> 

thanks for the reminder, I was waiting for 
https://github.com/ansible/ansible/issues/21547

to set min version to 2.5.2 but then it turned out that 2.5.2
didn't contain the fix, I'll set it to 2.5.3 if that version
contains the fix, otherwise I'll increase min version to 2.5.0
before that is fixed.

**Comment by ph3x** [comment]
Thanks for the heads up. Since I installed ansible via pip I have missed to upgrade it for some time :) Confirmed it's working again with 2.5.2

**Comment by nusenu** [comment]
OT: only now I realize that this has not been opened by ybid (I never got a notification email when this issue got reported - I'll look into that potential gh/email problem)
