### ISSUE TITLE
Add bandwidth limit

### ISSUE THREAD

**Issue by alanorth** [nusenu/ansible-relayor#172]
I set up a relay and blew through 1TB of bandwidth in five days so now my VPS quota is shot—so much for me helping the community! It might be good to have a sane default `MaxAdvertisedBandwidth`, or at least to add a note to README.md that urges users to set a limit.

The `torrc` man page suggests using 2 MBits if possible:

```
If you want to run a relay in the public network, this needs to be at the very least 75 KBytes for a relay (that is, 600 kbits) or 50 KBytes for a bridge (400 kbits) — but of course, more is better; we recommend at least 250 KBytes (2 mbits) if possible. (Default: 1 GByte)
```

**Comment by nusenu** [comment]
Hi Alan,

thanks for your request.

Tor will not limit its bandwidth usage by default,
we document this in the tor relay guide which can be found here:
https://trac.torproject.org/projects/tor/wiki/TorRelayGuide#Limitingbandwidthusageandtraffic

In a setup where you are only allowed to use 1TB/month
I recommend you use

https://www.torproject.org/docs/tor-manual.html.en#AccountingMax
which is supported by ansible-relayor via tor_AccountingMax

also: 
I opened a trac ticket to update the minimal values in the man page 
https://trac.torproject.org/projects/tor/ticket/26094

**Comment by alanorth** [comment]
Thanks for the reply, @nusenu.

So the `torrc` man page is out of date—ouch! Also, I only just now understood that `MaxAdvertisedBandwidth` is simply a _hint_ to the Tor network on how much traffic to send it, but doesn't actually limit the bandwidth rate.

I will look into using the `AccountingMax` settings.
