### ISSUE TITLE
hardenedbsd-11 fails due to missing libdl.so.1

### ISSUE THREAD

**Issue by Lirt** [nusenu/ansible-relayor#174]
Hi,

kitchen test with hardenedbsd-11 fails due to missing shared object `libdl.so.1`. 

```sh
$ bash
Shared object "libdl.so.1" not found, required by "bash"
$ python
Shared object "libdl.so.1" not found, required by "python"
```

I found similar bug on [FreeBSD bugzilla](https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=226200). I tried `pkg install -f` and also installing `gcc` and `build` but nothing seems to solve this issue.

I didn't find a way to find which package provides this file using `pkg`...

**Comment by nusenu** [comment]
see #165

we dropped support for hbsd

**Comment by Lirt** [comment]
Sorry for duplicate, present test in kitchen confused me. It's ok now 226009e441b0f0985e752aca067b4167f51bedf7.
