### ISSUE TITLE
Permission denied when enabling Control Socket

### ISSUE THREAD

**Issue by computeralex92** [nusenu/ansible-relayor#188]
**Describe the bug**
When enabling the Control Socket, the Tor Instances are not able to load the config because the folder permissions are not correct:

```
Oct 30 13:54:34 tor-relay03 Tor-IP_9000[3880]: Received reload signal (hup). Reloading config and resetting internal state.
Oct 30 13:54:34 tor-relay03 Tor-IP_9000[3880]: Read configuration file "/var/run/tor-instances/IP_9000.defaults".
Oct 30 13:54:34 tor-relay03 Tor-IP_9000[3880]: Read configuration file "/etc/tor/instances/IP_9000/torrc".
Oct 30 13:54:34 tor-relay03 Tor-IP_9000[3880]: sandbox_intern_string(): Bug: No interned sandbox parameter found for /var/run/tor-instances/IP_9000 (on Tor 0.3.4.8 )
Oct 30 13:54:34 tor-relay03 Tor-IP_9000[3880]: Directory /var/run/tor-instances/IP_9000 cannot be read: Permission denied
Oct 30 13:54:34 tor-relay03 Tor-IP_9000[3880]: Before Tor can create a control socket in "/var/run/tor-instances/IP_9000/control", the directory "/var/run/tor-instances/IP_9000" needs to exist, and to be accessible only by the user and group account that is running Tor.  (On some Unix systems, anybody who can list a socket can connect to it, so Tor is being careful.)
Oct 30 13:54:34 tor-relay03 Tor-IP_9000[3880]: Failed to parse/validate config: Failed to bind one of the listener ports.
Oct 30 13:54:34 tor-relay03 Tor-IP_9000[3880]: Reading config failed--see warnings above. For usage, try -h.
```

Here the folder permissions:

```
 /var/run/tor-instances # ls -la
total 8
drwxr-xr-x  4 root                    root                    120 Oct  6 16:13 .
drwxr-xr-x 21 root                    root                    780 Oct 30 14:39 ..
drwxr-sr-x  2 _tor-IP_9000 _tor-IP_9000  60 Oct 30 14:36 IP_9000
-rw-r--r--  1 root                    root                    517 Oct 30 14:36 IP_9000.defaults
drwxr-sr-x  2 _tor-IP_9100 _tor-IP_9100  60 Oct  6 16:13 IP_9100
-rw-r--r--  1 root                    root                    517 Oct  6 16:13 IP_9100.defaults
```

(IP is only a replacement)

**To Reproduce**
Configure a host and try to deploy the control socket on the machine.

**Expected behavior**
Control socket will be created and the instances are able to load the config.

**Version information (please include the following information):**
- ansible version:

```
ansible 2.7.1
config file = None
configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
ansible python module location = /usr/local/lib/python3.5/dist-packages/ansible
executable location = /usr/local/bin/ansible
python version = 3.5.3 (default, Sep 27 2018, 17:25:39) [GCC 6.3.0 20170516]
```

- ansible-relayor version: Master & 18.1.1

**Playbook information**

```
---

- hosts: all
  vars:
    tor_ContactInfo: example@example.com
    tor_enableControlSocket: true
  roles:
   - nusenu.relayor
```

**OS information**

Debian 9.5 (Control Machine & Relay Host)

**Debug information**
https://gist.github.com/computeralex92/141a7b49d74ef9bf28124a44b416682b

This Gist contains the output for a normal run without any problem; if needed, i will provide the output with the issue.

**Comment by nusenu** [comment]
Hi Alexander,

thanks for your report!

Alexander Lauster:
> Before Tor can create a control socket in "/var/run/tor-instances/IP_9000/control", the directory "/var/run/tor-instances/IP_9000" needs to exist

this appears to give me a clear indication for the root-cause.

expect a fix and new release within the next ten days.

**Comment by computeralex92** [comment]
Based on your questions and some search in the Tor Project Trac, I found the reason for the problems:
https://trac.torproject.org/projects/tor/ticket/28128

> Yeah... that part won't work. We can't add anything in the sandbox filters after initialization.
So until we get a better sandbox system, we'll have to document that Sandbox and client auth will work together but won't if a client is added at runtime (loaded with HUP).

Since I added the control socket after the first run of the Playbook, this "behavior" of the sandbox break the reload of the config.
After stoping all tor processes and start them again, the control socket was able to create without any problem.

A maybe workaround for this is, that the playbook check if a change in the sandbox is happen and if yes, a restart of the tor processes will happen; not a reload.

**Comment by nusenu** [comment]
Hi Alexander,

Alexander Lauster:
> Since I added the control socket after the first run of the Playbook,
> this "behavior" of the sandbox break the reload of the config. After
> stoping all tor processes and start them again, the control socket
> was able to create without any problem.

that is relevant info, thanks.

> A maybe workaround for this is, that the playbook check if a change
> in the sandbox is happen and if yes, a restart of the tor processes
> will happen; not a reload.

Since there are a few other cases in which a reload (instead of a restart) will
fail I considered to always do a restart if the file changed, dynamically selecting
reload vs. restart might get messy.

**Comment by nusenu** [comment]
the remaining steps will be covered in #189
