### ISSUE TITLE
Question about bandwidth and accounting max 

### ISSUE THREAD

**Issue by DigitalFriends** [nusenu/ansible-relayor#191]
Hi, i'm currently trying to figure out how to properly configure per instance bandwidth rates and accounting max but i cannot seem to be able to format the .csv file in a working manner.

I cannot find any examples of the supported format, could you point me in the right direction?

**Comment by nusenu** [comment]
Hi Paulo,

thanks for using relayor.

What would you like to do?

a) setting _one_ bw limit across all your relays

b) setting a specific bw limit per server (all tor instances on the server get the same value)

c) setting a specific bw limit per instance (different settings for across multiple tor instances on the _same_ server)

**Comment by DigitalFriends** [comment]
Hi, 

Thank you so much for taking your time to get back to me, your work is pure awesomeness. 

I would like to specify specific accounting limits and bw limits per host (got different vps providers with diff reqs) so i would say scenario C) will fit my needs the most. 

Thank you again.

**Comment by nusenu** [comment]
If you would like to have per host limits than it is (b)
and that is very easy to setup.


I'll give you an example.

Let's say you have two VPSes with the names:
my-fast-relay
and
my-slow-relay

Let's also assume you want to limit every tor instances on 'my-fast-relay' to 100 Mbit/s and 
my-slow-relay to 20 Mbits/s.


The easiest way to do this would be via host_vars:

the file:
host_vars/my-fast-relay
contains the line:
tor_RelayBandwidthRate 100 MBits

host_vars/my-slow-relay
contains the line:
tor_RelayBandwidthRate 20 MBits



the "host_vars" folder can be located in the folder where your inventory file or playbook file is

**Comment by DigitalFriends** [comment]
Thanks for the explanation!
Could i also add accounting limits in the same way?

Just to make sure, i'll create a file named the same as said host and then state the host specific settings inside that file, right?

**Comment by nusenu** [comment]
Paulo Aras wrote:
> Could i also add accounting limits in the
> same way?

yes, accounting related settings can be specified using the following variables:

tor_AccountingMax
tor_AccountingRule
tor_AccountingStart


> Just to make sure, i'll create a file named the same as said host and
> then state the host specific settings inside that file, right?

correct, just make sure the filename matches
the hostname as used in your ansible inventory file.

**Comment by DigitalFriends** [comment]
`ansiblemaster:~/relayor$ ansible-playbook playbook.yml -i hosts

PLAY [relays] **********************************************************************************************************************************

TASK [Gathering Facts] *************************************************************************************************************************
ERROR! failed to combine variables, expected dicts but got a 'dict' and a 'AnsibleUnicode':
{}
"tor_RelayBandwidthRate 100 MBits"`

I guess i have to start the file with `---`?

**Comment by nusenu** [comment]
sorry I was missing the ":"

nusenu-github@riseup.net:
> the file:
> host_vars/my-fast-relay
> contains the line:
> tor_RelayBandwidthRate 100 MBits

correction:
tor_RelayBandwidthRate: 100 MBits


> contains the line:
> tor_RelayBandwidthRate 20 MBits

tor_RelayBandwidthRate: 20 MBits

**Comment by DigitalFriends** [comment]
Okay great, i understand now. It's working!

Is there any nifty way to confirm that the changes were made? Maybe run with --check?

**Comment by DigitalFriends** [comment]
I see now, the changes were made :)


TASK [nusenu.relayor : Ensure torrc configuration file(s) are in place] ************************************************************************
changed: [my-fast-relay] => (item=[{u'ipv4': u'my-fast-relay.local', u'ipv6': u''}, {u'orport': 9000, u'dirport': 9001}])
changed: [my-fast-relay] => (item=[{u'ipv4': u'1my-fast-relay.local', u'ipv6': u''}, {u'orport': 9100, u'dirport': 9101}])
