### ISSUE TITLE
Consider enabling diff in ansible_push provisioner

### ISSUE THREAD

**Issue by Lirt** [nusenu/ansible-relayor#199]
I think that it would be nice to enable `diff: true` in `ansible_push` `provisioner` configuration.

This will make kitchen tests output file differences if there are any.

This will help us see what changes happened to files, if we are changing templates or different configurations and it will make us clearly see any errors, mistakes or typos during testing.

Example:
```bash
TASK [ansible-relayor : Create links to the service files (OpenBSD)] **********************************************************************************************************************************************
--- before
+++ after
@@ -1,4 +1,4 @@
 {
     "path": "/etc/rc.d/tor10_0_2_15_9000",
-    "state": "absent"
+    "state": "link"
 }

changed: [guard-openbsd] => (item=[{u'ipv4': u'10.0.2.15', u'ipv6': u''}, {u'orport': 9000, u'dirport': 9001}])
--- before
+++ after
@@ -1,4 +1,4 @@
 {
     "path": "/etc/rc.d/tor10_0_2_15_9100",
-    "state": "absent"
+    "state": "link"
 }
```

**Comment by nusenu** [comment]
very useful, thanks!

**Comment by Lirt** [comment]
PR in https://github.com/nusenu/ansible-relayor/pull/201

**Comment by nusenu** [comment]
thanks, merged.
