### ISSUE TITLE
How to undo or remove

### ISSUE THREAD

**Issue by drazisil** [nusenu/ansible-relayor#203]
I have managed to get my instances into a broken state. Is there a way to use this role to remove or do a full reinstall of tor on the hosts?

Failing that, is there an easy way to tell what was done / files created so I can remove manually?

**Comment by nusenu** [comment]
Please elaborate a bit, it is not possible for me to give a proper 
answer with the information you provided.
You description should include the answers
to the following questions:

- Did you use relayor to setup your relays in the first place
or 
- are you aiming to use relayor for the first time just to 
restore functionality?

- what do you mean by "broken state"?

- how does your setup look like?

**Comment by drazisil** [comment]
- Did you use relayor to setup your relays in the first place or - are you aiming to use relayor for the first time just to restore functionality? 

I initially used relayor 

- what do you mean by "broken state"? 

Turns out I just needed to manually update tor, as relayor  wasn't doing that

- how does your setup look like?

relayor was throwing errors and my replays were reporting as out of date

---------

I was looking for an uninstall or force reinstall. You can close this issue, or turn it into a feature request if you would like. My system is now working, but I think the feature would still be helpful.
