### ISSUE TITLE
galaxy fails to install role due to incompatible version formats

### ISSUE THREAD

**Issue by yokowka** [nusenu/ansible-relayor#204]
$ ansible-galaxy install nusenu.relayor
- downloading role 'relayor', owned by nusenu
 [WARNING]: - nusenu.relayor was NOT installed successfully: Unable to compare
role versions (v18.1.1, 0.1.0, v18.0.0, v0.3.0, v19.1.4, v19.1.0, v19.1.3,
0.2.0-rc, 0.1.0-alpha, v0.3.1, v0.3.3, v0.2.1, v19.1.2, v19.0.0, v0.3.2,
v19.1.1, v0.4.0, v18.1.0) to determine the most recent version due to
incompatible version formats. Please contact the role author to resolve
versioning conflicts, or specify an explicit role version to install.

upper after console command $ ansible-galaxy install nusenu.relayor

i want help Tor but this bug not it me allow

Debian 10 Buster Gnome

**Comment by nusenu** [comment]
until this gets fixed you can install it this way:

```
wget https://github.com/nusenu/ansible-relayor/archive/v19.1.6.tar.gz
mv v19.1.6.tar.gz nusenu.relayor
ansible-galaxy install nusenu.relayor 
```

**Comment by nusenu** [comment]
should be solved now, can you confirm?

**Comment by yokowka** [comment]
thank you. installed succesfuly!

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
пятница, 9 августа 2019 г., 21:49, nusenu <notifications@github.com> написано:
