### ISSUE TITLE
Cannot install on Oracle 8

### ISSUE THREAD

**Issue by tsekityam** [nusenu/ansible-relayor#221]
**Describe the bug**
Cannot install on Oracle 8 because `libsemanage-python` is no longer available

```
TASK [nusenu.relayor : Ensure SELinux dependencies are installed] ******************************************************************************************
fatal: [opc@152.70.103.215]: FAILED! => {"changed": false, "failures": ["libselinux-python All matches were filtered out by modular filtering for argument: libselinux-python", "No package libsemanage-python available."], "msg": "Failed to install some of the specified packages", "rc": 1, "results": []}
```

`libselinux-python` was renamed to `python3-libsemanage` in CentOS 8 or it's variants. So we need to check the major version of the OS, and install the correct version.

**Comment by tsekityam** [comment]
I apply the changes from https://github.com/bertvv/ansible-role-samba/issues/54#issuecomment-638256528, and I still got
```
fatal: [opc@152.70.103.215]: FAILED! => {"changed": false, "failures": ["No package libsemanage-python available."], "msg": "Failed to install some of the specified packages", "rc": 1, "results": []}
```

So we need to conditionally instal both package for CentOS 8

**Comment by nusenu** [comment]
Oracle 8 is not supported by this ansible role.

The supported operating systems are listed here:

https://github.com/nusenu/ansible-relayor#supported-operating-systems
