### ISSUE TITLE
Non-zero SocksPort

### ISSUE THREAD

**Issue by fyqwbdzsfjh** [nusenu/ansible-relayor#222]
Here it says that SocksPort should be zero:

https://github.com/nusenu/ansible-relayor/blob/4ef63b442ed307e9c5747045d9fcc5ad06e60f77/defaults/main.yml#L96-L98

Is that because in the case of multiple instances, the ports will collide? Should I manually generate a separate instance in case I want to have a socks proxy?

Unrelated to the issue: ansible-relayor is awesome. Thanks for all the good work!

**Comment by nusenu** [comment]
> Is that because in the case of multiple instances, the ports will
> collide? 

correct.

> Should I manually generate a separate instance in case I
> want to have a socks proxy?

yes, that is the best way to do it.

**Comment by fyqwbdzsfjh** [comment]
Thanks!
