### ISSUE TITLE
New relay installation fails when using --tags debian

### ISSUE THREAD

**Issue by jn9999** [nusenu/ansible-relayor#224]
**Describe the bug**
Installing a new relay on Debian fails unless running without the debian tag once to configure the Torpoject Debian repository.

Removing the deb.torproject.org-keyring package dependency in nusenu.relayor/vars/os_Debian.yml solves this (only tested with Debian 11) but will create relays that fall behind the latest Tor version. Should --tags not be used on the first run or the tasks in nusenu.relayor/tasks/apt_prepare.yml also happen when running with --tags debian?

**To Reproduce**
Run against a newly installed Debian machine:
`ansible-playbook --tags debian 1_contactInfo.yml`

**Expected behavior**
The machine should become a relay without any error.

**Version information (please include the following information):**
- ansible version 2.10.8
- ansible-relayor version v21.1.0

**Playbook information**

> ---
> 
> - hosts: relays
>   vars:
>     tor_ContactInfo: relayor-example@example.com
>   roles:
>    - nusenu.relayor

**OS information**
Target was Debian 11.

**Debug information**
`TASK [nusenu.relayor : Ensure tor is installed] *******************************************************************************************************************************************************************************************************
Saturday 13 November 2021  05:09:58 +0100 (0:00:00.040)       0:00:03.208 ***** 
failed: [example.com] (item=deb.torproject.org-keyring) => {"ansible_loop_var": "item", "changed": false, "item": "deb.torproject.org-keyring", "msg": "No package matching 'deb.torproject.org-keyring' is available"}
changed: [example.com] => (item=tor)
ok: [example.com] => (item=tor-geoipdb)

PLAY RECAP ********************************************************************************************************************************************************************************************************************************************
example.com              : ok=10   changed=0    unreachable=0    failed=1    skipped=4    rescued=0    ignored=0   
`

**Comment by nusenu** [comment]
Thanks for taking the time to report this issue.

It has been fixed now.
The fix will be included in the next release.
