### ISSUE TITLE
Debian package deb.torproject.org-keyring doesn't exist for armhf

### ISSUE THREAD

**Issue by whowantsmybigdata** [nusenu/ansible-relayor#232]
During the apt install of `deb.torproject.org-keyring` there is a problem if the node machine is running on 32-bit Arm (Raspberry Pi). There is no package for armhf so the playbook fails. 

Commenting the line `deb.torproject.org-keyring` in `roles/vars/main.yml` solves the issue. 

Is this somehow a security issue while running the tor node?

Thanks for this easy solution in setting up and a new relay!

**Comment by nusenu** [comment]
This is best asked upstream if this is still an issue.
Upstream documentation:
https://support.torproject.org/apt/tor-deb-repo/
