### ISSUE TITLE
Specifying accounting settings seems to have no effect

### ISSUE THREAD

**Issue by danielw97** [nusenu/ansible-relayor#243]
Hi there,
I've come to this utility recently, and so far it seems to be working quite well.
However one issue I'm running into is that setting "tor_AccountingMax: 325 GBytes" or similar in my vars section of yaml doesn't seem to update the torrc files on the target machines as I would expect.
Is this something I'm doing incorrectly, or is there a better/alternative way to manage accounting?
Thanks.

**Comment by nusenu** [comment]
Hi danielw97,

there is no such var as "tor_AccountingMax".

Have you tried setting it via

tor_config:
   tor_AccountingMax: 325 GBytes


If it does not work, please use the issue submitting template.

**Comment by nusenu** [comment]
actually:
```
tor_config:
  AccountingMax: 325 GBytes
```

**Comment by danielw97** [comment]
Thanks very much, that fixed it.
The problem was largely down to my unfamiliarity with the way the .yaml file is structured, although I think I have a better grasp of it now thanks to your comment.
Appreciate the fast reply as well.
