### ISSUE TITLE
Changing one relay to exit seems to have no effect

### ISSUE THREAD

**Issue by danielw97** [nusenu/ansible-relayor#244]
**Describe the bug**
Hi again,
This very well may be something I'm doing incorrectly, however thought I would reach out and I hope that's okay.
I'm currently trying to switch only one of my instances into an exit node, and think I am quite close.
I've defined the tor_ExitRelay and tor_ExitRelaySetting_file as well as my abuse contact email which I can see reflected in the exit notice html.
My setting file looks like this:
ip_9000,exit
This seems to all execute fine, although my torrc in that instance doesn't seem to update correctly.
I'm not sure if there is anything you think I might be doing wrong here?
**To Reproduce**
See above.

**Expected behavior**
The torrc on the target relay should be updated.

If there isn't something I'm apparently doing wrong I'll include more debug info, although I suspect this may be a simple fix on my end as I'm getting used to the software.

**Comment by danielw97** [comment]
Hi again,
I'm going to put the file I'm using for configuration below, if that helps:

---

- hosts: relays
  vars:
    tor_ContactInfo: redacted
    tor_ExitRelay: true
    tor_ExitRelaySetting_file: ~/ansible/exits
    tor_AbuseEmailAddress: redacted
    tor_config:
      AccountingMax: 325 GBytes
  roles:
   - nusenu.relayor

**Comment by nusenu** [comment]
General remark:
These types of questions to not appear to be bug reports for github issues.

I'm mentioning the alternative options for these support questions for future questions:

* use the email support option https://github.com/nusenu/ansible-relayor#ansible-relayor
* use github discussions https://github.com/nusenu/ansible-relayor/discussions


About your question:

If you have multiple servers and each server has a single tor instance only, you probably do not need to use
tor_ExitRelaySetting_file at all just use tor_ExitRelay in the context of a host_var of the specific server you want
to turn into an exit.

If you still want to use tor_ExitRelaySetting_file:
ensure the first column in that csv file matches the subfolder names
in  ~/.tor/offlinemasterkeys

you can start generating the first column with
ls .tor/offlinemasterkeys > ~/ansible/exits
add commas and "exit" in that file manually.

Set tor_ExitRelaySetting_file to an absolute path without using a "~" character.

Set tor_ExitRelay in host_vars context not directly in the playbook vars.

Hope this helps!

**Comment by danielw97** [comment]
Appreciate the response, if any other issues that aren't directly bug reports come up I'll be sure to use those alternative avenues.
