### ISSUE TITLE
add support for per instance nicknames

### ISSUE THREAD

**Issue by nusenu** [nusenu/ansible-relayor#43]

**Comment by CristianCantoro** [comment]
Strong +1, a source could be the hostname.

**Comment by nusenu** [comment]
hi,
host-level granularity is already available - you can use tor_nickname for that (with for example ansible_hostname).

This entry is about instance-level granularity.

**Comment by CristianCantoro** [comment]
I see, that is useful as well.

**Comment by nusenu** [comment]
It is implemented (uncommited) but requires users to manually apply this ansible bugfix:
//github.com/ansible/ansible/issues/12062
https://github.com/ansible/ansible/commit/b2bfe3502b1bb73927d08ea0fcf964a508129267
