### ISSUE TITLE
Upload to Ansible Galaxy so that people can find it there

### ISSUE THREAD

**Issue by ypid** [nusenu/ansible-relayor#46]
To avoid looking into deprecated/unmaintained stuff (ref: https://github.com/david415/ansible-tor/pull/8)

Also, what are your thoughts on [ansigenome](https://github.com/nickjj/ansigenome), [rolespec](https://github.com/nickjj/rolespec) and Travis CI.

I will look into your modifications and compare them with what I did with the david415.tor role lately.

PS: Why did you not just fork https://github.com/david415/ansible-tor and instead did `git init && git add .`?

**Comment by nusenu** [comment]
Hi,
thanks for your input.
I assume people looking for a tor related role on galaxy will search for 'tor' on galaxy. If they are lucky they will find David's role on page two of the search results. His readme points to this project.

(I actually had 'put it on galaxy' on the todo list once a few specific bugs are fixed but with David's latest commit pointing to relayor and galaxy's move to require oauth I'm no longer aiming for it.)

**Comment by ypid** [comment]
Uploading your role to Ansible Galaxy is easy but I personally don’t need it on there. Your argument that davids role refers to your role is only partially true because he closed the issue [Update role on Ansible Galaxy](https://github.com/david415/ansible-tor/issues/9) so that [Galaxy](https://galaxy.ansible.com/list#/roles/592) has no hint to your role.

**Comment by nusenu** [comment]
https://galaxy.ansible.com/list#/roles/592 -> links to 
https://github.com/david415/ansible-tor -> links to
https://github.com/nusenu/ansible-relayor

> Uploading your role to Ansible Galaxy is easy but I personally don’t need it on there.

So we can close this ticket?

**Comment by ypid** [comment]
I would prefer it when @david415 just properly handles https://github.com/david415/ansible-tor/issues/9

**Comment by nusenu** [comment]
https://galaxy.ansible.com/nusenu/relayor/
