### ISSUE TITLE
rename 'configure' tag to 'setfam'

### ISSUE THREAD

**Issue by nusenu** [nusenu/ansible-relayor#47]

**Comment by oguya** [comment]
Why would you like to rename `configure` tag to `setfam` ? And does the rename apply to all tasks with that specific tag name or just a chosen few tasks ?

**Comment by nusenu** [comment]
the name 'configure' suggests that you can do a --tags install,configure but that will fail. 
To make this a bit more obvious I renamed it to 'reconfigure' (setfam is to specific because it generates the entire torrc).
