### ISSUE TITLE
Add Family variable to list other family members other then the one where Tor is being installed

### ISSUE THREAD

**Issue by CristianCantoro** [nusenu/ansible-relayor#48]
As per subject, if an operator already has other nodes and want to launch a new node (or group of nodes) it should be possible to specify the other nodes fingerprint to be added to the `MyFamily` configuration in addition to the automatic discovery of the hosts in the group.

**Comment by nusenu** [comment]
hi,
I see your point. Does the reconfigure tag not satisfy your needs?
(I guess manually specifying 'other' relay fingerprints, will be more error prone)

**Comment by nusenu** [comment]
The new approach in the offlinemasterkey branch makes it really easy to add arbitrary fingerprints
Simply add one fingerprint per line in (in the second column separated by " "):
~/.tor/offlinmasterkeys/123/fingerprint
