### ISSUE TITLE
Add example playbooks

### ISSUE THREAD

**Issue by CristianCantoro** [nusenu/ansible-relayor#51]
Having examples in the README is useful, but I think that it would be better to have complete playbooks with comments with clear instructions on how to use them directly in the repo. I will provide a new pull request if this idea is accepted.

**Comment by nusenu** [comment]
Hi,
to what extend are the examples in the README not 'complete'?

**Comment by nusenu** [comment]
https://github.com/nusenu/ansible-relayor/wiki/relayor-playbook-examples
