### ISSUE TITLE
Allow binding to privileged ports

### ISSUE THREAD

**Issue by corny** [nusenu/ansible-relayor#64]
I use `setcap` to allow binding to privileged ports in my unit file:
https://github.com/digineo/ansible-tor/blob/master/files/tor.service

**Comment by nusenu** [comment]
Using ports <1024 for OrPort/DirPort works. Are you having problems with that?

Also note: We use the packager's service files and no longer ship our own service files.

**Comment by nusenu** [comment]
This issue does not affect this ansible role.
