### ISSUE TITLE
Bridge support

### ISSUE THREAD

**Issue by parmegv** [nusenu/ansible-relayor#69]
Hi,

 I was wondering, why did you remove the obfs4proxy bridge support? It would be nice to have it somewhere, perhaps you think it is not appropriate to put it in ansible-relayor because it should be a repo on its own. Is it that the case?

 Thanks for your work!

**Comment by nusenu** [comment]
You are right, this ansible role is specifically for relays only. A ansible role for bridges would be a separate role.
