### ISSUE TITLE
bring SyslogIdentityTag to OpenBSD

### ISSUE THREAD

**Issue by nusenu** [nusenu/ansible-relayor#71]
SyslogIdentityTag was only in debian as of 0.2.7.x.

As soon as tor 0.2.8.x packages are available for other platforms add it to them and require tor min. version 0.2.8.x

**Comment by nusenu** [comment]
Fedora/CentOS:
https://bugzilla.redhat.com/show_bug.cgi?id=1284469
https://bugzilla.redhat.com/show_bug.cgi?id=1364772

**Comment by nusenu** [comment]
All supported Linux distributions + FreeBSD have tor 0.2.8.x now, so the only remaining platform blocking this to be enabled globally is OpenBSD. 
We will have to wait for the next OpenBSD release (6.1).

**Comment by ypid** [comment]
> As soon as tor 0.2.8.x packages are available for other platforms add it to them and require tor min. version 0.2.8.x

You could check the `tor` version in the template and only include the directive if the version requirement is satisfied. In DebOps we tent to use Ansible local facts to even allow other roles to check installed versions.
Examples:

* https://github.com/debops/ansible-pki/pull/90
* https://github.com/debops/ansible-redis/blob/master/templates/etc/ansible/facts.d/redis.fact.j2

Ansible also has a `version_compare` Jinja filter. Maybe that is also useful for this role.

**Comment by nusenu** [comment]
Yes I know that this feature could be enabled opportunistically - but I would simply check for if os != OpenBSD.
This ticket is for the global switch though.
