### ISSUE TITLE
Integrating the role into DebOps

### ISSUE THREAD

**Issue by ypid** [nusenu/ansible-relayor#75]
Hi

I wanted to ask if there is an interest from your side in moving this role to [DebOps](https://github.com/debops/) and adapting it to the standards of DebOps (documentation)? You can have a look at [debops.nullmailer](https://github.com/debops/ansible-nullmailer) and [Role guidelines](https://wiki.debops.org/debops-contrib:start) to get an idea how this could look like.

This would allow DebOps users to easily run a Tor Relay. For the current user, the role can still be used as standalone role. When the role gets moved, GitHub would redirect to the new location.

Checklist and needed changes:

- [x] License: GPL-3.0
- [ ] Configure iptables packet filter with [debops.ferm](https://github.com/debops/ansible-ferm/) if the role runs under DebOps
- [ ] Adapt to the DebOps standards
- [ ] Move to DebOps

Let me know what you think and thanks for you work.

**Comment by nusenu** [comment]
Hi,

I don't see any benefit in moving this elsewhere.

**Comment by ypid** [comment]
Fair enough. I see a few advantages:

* Better documentation
* Variable name space, which makes it easy to use the role in larger Ansible setups (all variables `relayor__`).
* Makes it easier for DebOps users to run a Tor Relay

But you are right. That would require some work and for you to adapt to the new format. So I understand your concern.

Could I maybe add the ferm depend variables ([example](https://github.com/debops/ansible-nullmailer/blob/360ff49f7d9f91feebf5d3ce9bbcf9e2e80c0f69/defaults/main.yml#L320-L330)) to the default file and then do everything else at the playbook level in https://github.com/debops-contrib/debops-contrib-playbooks ?

**Comment by ypid** [comment]
> Documentation quality does not improve just because the repo is moved somewhere else - I guess ;)

Right :wink: I could bring the role up to the DebOps standards and maintain it in DebOps.

> I prefer to keep it a standalone role and as the name "debops" says it is debian specific - relayor isn't. I'm about to close this issue, nonetheless thanks for your input.

OK. I understand your point. Note that [ferm](http://ferm.foo-projects.org/) itself is not Debian specific and in DebOps we consider the Firewall to be in scope of roles but I understand that this does not work for single because as you can not make assumptions how packet filters are configured in this case.

Concluding from that I will probably maintain support for this role at the playbook level in [debops-contrib](https://github.com/debops-contrib/) for now. Thanks!

You can close the issue now or I will close it when I had time to test it and add a playbook to debops-contrib.
