### ISSUE TITLE
style: use YAML syntax (better syntax highlighting)

### ISSUE THREAD

**Issue by nusenu** [nusenu/ansible-relayor#76]
also mentioned in #75 

http://blog.bandwidth.com/why-you-should-use-yaml-as-yaml-with-ansible/

**Comment by ypid** [comment]
Ansible core people finally also realized that YAML syntax is nice :wink: https://www.ansible.com/blog/ansible-best-practices-essentials

**Comment by nusenu** [comment]
apparently a important thing to consider when migrating:
mode=700
!= 
mode: 700

correct:
mode: 0700

**Comment by nusenu** [comment]
The YAML_syntax branch needs some more testing since it touches a lot of lines and then it should be ready to merge.
