### ISSUE TITLE
prefix vars to avoid namespace clashes

### ISSUE THREAD

**Issue by nusenu** [nusenu/ansible-relayor#77]
Follow best practices and prefix your role variables.

mentioned in #75 and
https://galaxy.ansible.com/intro

I find "relayor_" a rather long prefix and would prefer "tor_" or "torr_" (short tor relay), because I guess it is unlikely that people will run multiple tor roles.

Note: This change will **break existing setups** since they will have to update their playbooks.

For this reason we will commit this once we start to require tor v0.2.8.x (see #71 )

**Comment by ypid** [comment]
Note that DebOps has a procedure in place to do variable renames (ref: [Migration/upgrade notes](https://github.com/debops/docs/issues/160)) so this could be semi-automated and users only have to run a command.

About the name, I would not mind so much to keep the variable names to a minimum but that might come from my practice to copy/paste variables from the default file and then modifying them. Also, I would prefer a more descriptive role name which could then also be used for the variables, like `nusenu.tor_relay` and then using the name space `tor_relay__` for the role (the `__` comes from DebOps and was introduced to make working with role dependencies visible). Anyway.

If the only reason to not use `relayor_` or `relayor__` is the length then this might be debatable (we are talking 8 against 5 characters here) :smile:

@nusenu BTW: I like how you handle the release management :wink:
