### ISSUE TITLE
Debian variables not loaded

### ISSUE THREAD

**Issue by kstrel** [nusenu/ansible-relayor#86]
When I run

`ansible-playbook -i hosts tor.yml --tags debian`

on a fresh Ubuntu Server 16.04 install, I get the following error

`TASK [relayor : Ensure per-instance config folders exist (Debian only)] ********
fatal: [192.168.0.15]: FAILED! => {"failed": true, "msg": "the field 'args' has an invalid value, which appears to include a variable that is undefined. The error was: 'tor_ConfDir' is undefined\n\nThe error appears to have been in '/home/kirill/torrelay/roles/relayor/tasks/configure.yml': line 73, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Ensure per-instance config folders exist (Debian only)\n  ^ here\n"}`

The issue is fixed by adding 
> - include_vars: "Debian.yml"
  tags:
    - debian

to `tasks/main.yml`. 

The OS specific variables do not seem to be loaded correctly.

**Comment by nusenu** [comment]
Thank you for your report! 
Should be fixed now.
