### ISSUE TITLE
macOS specific local requirements for mention in README

### ISSUE THREAD

**Issue by rdkr** [nusenu/ansible-relayor#90]
Another macOS quirk I found yesterday - there is no `sha1sum` by default on macOS, as required for the checks in `tasks/configure.yml`.

The local requirements to run this role were satisfied on my system by:

    brew install tor
    brew install md5sha1sum

This may be worth mentioning in the README, as it initially seemed from the output that the cause of failure was duplicate keys.

**Comment by nusenu** [comment]
Thanks for your feedback.

I added the list of commands we execute on the control machine to the requirements (tor is already on the list).

**Comment by rdkr** [comment]
I'm happy to help! I had `netaddr` already and installed `tor` based on the README, so in this case only `sha1sum` was an issue when running.

**Comment by nusenu** [comment]
Could you test 16b89cafbccd674140ed2f85cc9aa3088af0618c with and without sha1sum installed and let me know if it works as expected? thanks

**Comment by nusenu** [comment]
user disappeared - lets consider this done

**Comment by rdkr** [comment]
Hi. 16b89ca does not work due to inconsistent exit codes or the `--version` option not existing. I will look into alternatives.

`sha256sum` is not available by default. Two possible cross platform alternatives are `cksum` and `openssl sha1`. Shall we discuss this in a new issue?
